import { Amplify } from 'aws-amplify';
import { generateClient } from 'aws-amplify/api';
import type { AppData } from './types';
// Generated by `npx ampx sandbox` — imported at build time so it's always available,
// unlike a runtime fetch which fails because the file isn't in public/
import amplifyOutputs from '../amplify_outputs.json';

const CLOUD_RECORD_ID = 'lift-log-app-data';
let didConfigure = false;

function configureAmplify() {
  if (didConfigure) {
    return;
  }

  Amplify.configure(amplifyOutputs as any);
  didConfigure = true;
}

export async function loadAppDataFromCloud(): Promise<AppData | null> {
  configureAmplify();

  try {
    const client = generateClient();
    const result = await client.graphql({
      query: /* GraphQL */ `
        query ListAppDataRecords($filter: ModelAppDataRecordFilterInput) {
          listAppDataRecords(filter: $filter) {
            items {
              id
              payload
            }
          }
        }
      `,
      variables: {
        filter: { id: { eq: CLOUD_RECORD_ID } },
      },
    }) as { data?: { listAppDataRecords?: { items?: Array<{ id: string; payload: string }> } } };

    const record = result.data?.listAppDataRecords?.items?.[0];
    if (!record?.payload) {
      console.log('[Cloud] No data found in cloud');
      return null;
    }

    console.log('[Cloud] Loaded data from cloud');
    return JSON.parse(record.payload) as AppData;
  } catch (error) {
    console.error('[Cloud] Failed to load from cloud:', error);
    return null;
  }
}

export async function saveAppDataToCloud(data: AppData) {
  configureAmplify();

  try {
    const client = generateClient();
    const payload = JSON.stringify(data);

    const existing = await loadAppDataFromCloud();
    if (existing) {
      console.log('[Cloud] Updating existing cloud record');
      await client.graphql({
        query: /* GraphQL */ `
          mutation UpdateAppDataRecord($input: UpdateAppDataRecordInput!) {
            updateAppDataRecord(input: $input) {
              id
              payload
            }
          }
        `,
        variables: {
          input: {
            id: CLOUD_RECORD_ID,
            payload,
          },
        },
      });
      return;
    }

    console.log('[Cloud] Creating new cloud record');
    await client.graphql({
      query: /* GraphQL */ `
        mutation CreateAppDataRecord($input: CreateAppDataRecordInput!) {
          createAppDataRecord(input: $input) {
            id
            payload
          }
        }
      `,
      variables: {
        input: {
          id: CLOUD_RECORD_ID,
          payload,
        },
      },
    });
    console.log('[Cloud] Successfully saved data to cloud');
  } catch (error) {
    // Fall back to local storage if the cloud backend is unavailable.
    console.error('[Cloud] Failed to save to cloud:', error);
  }
}
